version: "3.9"
services:
  web:
    extends:
      file: web.yml
      service: web

  db:
    # We use the predefined Postgres image
    image: postgres:13-alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  db-migrations:
    extends:
      file: web.yml
      service: web
    command: ./bin/goslash eval "Goslash.ReleaseTasks.migrate"
    depends_on:
      - web
    profiles:
      - tools

volumes:
  pgdata:
